export const skillMenu = [
  { id: 19, value: 'React.js' },
  { id: 20, value: 'Angular.js' },
  { id: 21, value: 'Node' },
  { id: 25, value: 'Express.js' },
];

export const years = [
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
  '2023',
  '2024',
  '2025',
  '2026',
  '2027',
  '2028',
  '2029',
  '2030'
];

export const grade = [
  { id: 1, value: 'A+' },
  { id: 2, value: 'A' },
  { id: 3, value: 'B' },
  { id: 4, value: 'C' },
  { id: 5, value: 'D' },
  { id: 6, value: 'E' }
];

export const locationData = [
  { id: 1, value: 'New York' },
  { id: 2, value: 'London' },
  { id: 3, value: 'Indore' },
  { id: 4, value: 'Florida' },
  { id: 5, value: 'Washington' },
  { id: 6, value: 'Banglore' }
];

export const sectorsData = [
  { id: 1, value: 'Information Technology' },
  { id: 2, value: 'Automobile' },
  { id: 3, value: 'Robotics' }
];

export const keywordsData = [
  { id: 15, value: 'Job' },
  { id: 16, value: 'Fresher' },
  { id: 18, value: 'Entry Level' },
  { id: 19, value: 'Experienced' }
];

export const subjectMenu = [
  { id: 1, value: 'Accounting' },
  { id: 2, value: 'Afrikaans' },
  { id: 3, value: 'Ancient History' },
  { id: 4, value: 'Anthropology' },
  { id: 5, value: 'Applied Art and Design' },
  { id: 6, value: 'Applied Business' },
  { id: 7, value: 'Applied ICT' },
  { id: 8, value: 'Applied Science' },
  { id: 9, value: 'Arabic' },
  { id: 10, value: 'Archaeology' },
  { id: 11, value: 'Art and Design' },
  { id: 12, value: 'Anatomy' },
  { id: 13, value: 'Bengali' },
  { id: 14, value: 'Biblical Hebrew' },
  { id: 15, value: 'Biology' },
  { id: 16, value: 'Business' },
  { id: 17, value: 'Business Studies' },
  { id: 18, value: 'Chemistry' },
  { id: 19, value: 'Chinese' },
  { id: 20, value: 'Citizenship Studies' },
  { id: 21, value: 'Classical Civilisation' },
  { id: 22, value: 'Classical Greek' },
  { id: 23, value: 'Classical Studies' },
  { id: 24, value: 'Communication and Culture' },
  { id: 25, value: 'Computer Science' },
  { id: 26, value: 'Computing' },
  { id: 27, value: 'Creative Writing' },
  { id: 28, value: 'Critical Thinking' },
  { id: 29, value: 'Dance' },
  { id: 30, value: 'Design and Technology' },
  { id: 31, value: 'Design and Textiles' },
  { id: 32, value: 'Digital Media and Design' },
  { id: 33, value: 'Digital Technology' },
  { id: 34, value: 'Divinity' },
  { id: 35, value: 'Drama' },
  { id: 36, value: 'Drama and Theatre' },
  { id: 37, value: 'Dutch' },
  { id: 38, value: 'Economics' },
  { id: 39, value: 'Economics and Business' },
  { id: 40, value: 'Electronics' },
  { id: 41, value: 'Engineering' },
  { id: 42, value: 'English Language' },
  { id: 43, value: 'English Language and Literature' },
  { id: 44, value: 'English Literature' },
  { id: 45, value: 'Environmental Science' },
  { id: 46, value: 'Environmental Studies' },
  { id: 47, value: 'Environmental Technology' },
  { id: 48, value: 'Fashion and Textiles' },
  { id: 49, value: 'Film Studies' },
  { id: 50, value: 'Food Studies' },
  { id: 51, value: 'Food Technology' },
  { id: 52, value: 'French' },
  { id: 53, value: 'Further Mathematics' },
  { id: 54, value: 'General Studies' },
  { id: 55, value: 'Geography' },
  { id: 56, value: 'Geology' },
  { id: 57, value: 'German' },
  { id: 58, value: 'Global Development' },
  { id: 59, value: 'Global Perspectives and Research' },
  { id: 60, value: 'Government and Politics' },
  { id: 61, value: 'Greek' },
  { id: 62, value: 'Gujarati' },
  { id: 63, value: 'Health and Social Care' },
  { id: 64, value: 'Hindi' },
  { id: 65, value: 'Hinduism' },
  { id: 66, value: 'History' },
  { id: 67, value: 'History of Art' },
  { id: 68, value: 'Home Economics' },
  { id: 69, value: 'Human Biology' },
  { id: 70, value: 'Humanities' },
  { id: 71, value: 'ICT' },
  { id: 72, value: 'Information Technology' },
  { id: 73, value: 'Irish' },
  { id: 74, value: 'Islamic Studies' },
  { id: 75, value: 'Italian' },
  { id: 76, value: 'Japanese' },
  { id: 77, value: 'Journalism' },
  { id: 78, value: 'Latin' },
  { id: 79, value: 'Law' },
  { id: 80, value: 'Leisure Studies' },
  { id: 81, value: 'Life and Health Sciences' },
  { id: 82, value: 'Marine Science' },
  { id: 83, value: 'Mathematics' },
  { id: 84, value: 'Media Studies' },
  { id: 85, value: 'Modern Hebrew' },
  { id: 86, value: 'Modern Languages' },
  { id: 87, value: 'Moving Image Arts' },
  { id: 88, value: 'Music' },
  { id: 89, value: 'Music Technology' },
  { id: 90, value: 'Nutrition and Food Science' },
  { id: 91, value: 'Punjabi' },
  { id: 92, value: 'Performance Studies' },
  { id: 93, value: 'Performing Arts' },
  { id: 94, value: 'Persian' },
  { id: 95, value: 'Philosophy' },
  { id: 96, value: 'Photography' },
  { id: 97, value: 'Physical Education' },
  { id: 98, value: 'Physical Science' },
  { id: 99, value: 'Physics' },
  { id: 100, value: 'Polish' },
  { id: 101, value: 'Politics' },
  { id: 102, value: 'Portuguese' },
  { id: 103, value: 'Product Design' },
  { id: 104, value: 'Professional Business Services' },
  { id: 105, value: 'Psychology' },
  { id: 106, value: 'Pure Mathematics' },
  { id: 107, value: 'Quantitative Methods' },
  { id: 108, value: 'Religious Studies' },
  { id: 109, value: 'Russian' },
  { id: 110, value: 'Science in Society' },
  { id: 111, value: 'Sociology' },
  { id: 112, value: 'Software Systems Development' },
  { id: 113, value: 'Spanish' },
  { id: 114, value: 'Sports Science' },
  { id: 115, value: 'Statistics' },
  { id: 116, value: 'Systems and Control Technology' },
  { id: 117, value: 'Tamil' },
  { id: 118, value: 'Technology and Design' },
  { id: 119, value: 'Thinking Skills' },
  { id: 120, value: 'Travel and Tourism' },
  { id: 121, value: 'Turkish' },
  { id: 122, value: 'Urdu' },
  { id: 123, value: 'Welsh' },
  { id: 124, value: 'World Development' }
];
